### ISSUE TITLE
Upcoming Versions

### ISSUE THREAD

**Issue by re4jh** [OXID-eSales/gdpr-base-module#1]
- I completeley understand what OXID eShop 5.3.7/4.10.7 and following means
- But what does "upcoming 5.3.x/4.7.x versions/releases" mean?
- Will you really support Versions >= 4.7.x and newer?
- Is the left version number for CE and the right one for PE/EE releases?
- At the moment I have an 4.9.9 CE needing stuff for GDPR. Is there any chance to get this Version supported?

_Anybody selling me some hope?_

**Comment by MantasVaitkunas** [comment]
Hi, thanks for noticing the mistake. I just updated README.md file.
