### ISSUE TITLE
clean up session variable "deladrid" in oeGdprBaseOxcmp_user::oeGdprBaseDeleteShippingAddress

### ISSUE THREAD

**Issue by kaluzki** [OXID-eSales/gdpr-base-module#2]
https://github.com/OXID-eSales/gdpr-base-module/blob/ae762fedd079050811ef90f370f2edc840d51055/source/modules/oe/oegdprbase/components/oegdprbaseoxcmp_user.php#L40

**Comment by Sieg** [comment]
Hello @kaluzki, Could you please provide some list of issues because of not removing the mentioned variable?

**Comment by Sieg** [comment]
Hello @kaluzki, closing the issue due to inactivity. If you feel the issue still viable, please report it at https://bugs.oxid-esales.com
