### ISSUE TITLE
why so complicated?

### ISSUE THREAD

**Issue by vanilla-thunder** [OXID-eSales/gdpr-base-module#3]
This module contains 84 files in 54 folders.
Was all this stuff really necessary for adding three simple functions?

**Comment by Sieg** [comment]
Hello @vanilla-thunder, Module provides functionality which allows:

* To control recommendation function via OXID eShop admin.
* Users to manage their reviews.
* Users to delete their shipping addresses.
* Users to delete their account.

It is at least 4, not simple, functions. 

Please consider making a pull request if you have suggestions for improvements ;)
